/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'id' : bigint,
  'status' : InquiryStatus,
  'emailOrPhone' : string,
  'name' : string,
  'createdAt' : bigint,
  'seenByAdmin' : boolean,
  'company' : [] | [string],
  'message' : string,
  'inquiryTopic' : string,
}
export type InquiryStatus = { 'closed' : null } |
  { 'pending' : null } |
  { 'open' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInquiry' : ActorMethod<
    [string, [] | [string], string, string, string],
    [] | [bigint]
  >,
  'deleteInquiry' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInquiry' : ActorMethod<[bigint], [] | [Inquiry]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listInquiries' : ActorMethod<[bigint, bigint], Array<Inquiry>>,
  'markInquiryAsSeen' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateInquiryStatus' : ActorMethod<[bigint, InquiryStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];